### ISSUE TITLE
No attribute `Morphology`

### ISSUE THREAD

**Issue by dilawar** [aviralg/moogli#5]
I used `python setup.py install` and run the following script.

```
python insertSpines.py 
In doLoadModel for SWC
ReadSwc: barrionuevo_cell1zr.CNG.swc    : NumSegs = 2246, bad = 0, Validated = 1, numBranches = 147
ReadSwc::diagnostics: undef :   0
ReadSwc::diagnostics: soma :    1
ReadSwc::diagnostics: axon :    221
ReadSwc::diagnostics: dend :    785python insertSpines.py 
In doLoadModel for SWC
ReadSwc: barrionuevo_cell1zr.CNG.swc    : NumSegs = 2246, bad = 0, Validated = 1, numBranches = 147
ReadSwc::diagnostics: undef :   0
ReadSwc::diagnostics: soma :    1
ReadSwc::diagnostics: axon :    221
ReadSwc::diagnostics: dend :    785
ReadSwc::diagnostics: apical :  1093
ReadSwc::diagnostics: dend_f :  23
ReadSwc::diagnostics: dend_e :  29
ReadSwc::diagnostics: custom :  0
ReadSwc::diagnostics: bad : 0
ReadSwc::diagnostics: undef :   0
ReadSwc::diagnostics: axon_f :  6
ReadSwc::diagnostics: axon_e :  7
ReadSwc::diagnostics: apical_f :    40
ReadSwc::diagnostics: apical_e :    41
Rdesigneur: Elec model has 2246 compartments and 3795 spines on 0 compartments.
Traceback (most recent call last):
  File "insertSpines.py", line 84, in <module>
    main()
  File "insertSpines.py", line 60, in main
    morphology = moogli.read_morphology_from_moose(name = "", path = "/model/elec")
  File "/home_local/dilawars/Work/GITHUB/BhallaLab/moogli/moogli/main.py", line 80, in read_morphology_from_moose
    morphology = _moogli.Morphology(name, 1)
AttributeError: 'module' object has no attribute 'Morphology'

```

I'll wait till Travis builds are OK.

**Comment by aviralg** [comment]
Update the library properly. You need to use the geometry branch. Also remember to update moose-examples.

**Comment by dilawar** [comment]
Fixed.
